model_dir: model

data:
  train_features_file: logic-train.encoded.txt
  train_labels_file: english-train.encoded.txt
  eval_features_file: logic-val.encoded.txt
  eval_labels_file: english-val.encoded.txt
  source_words_vocabulary: en_logic.vocab
  target_words_vocabulary: en_logic.vocab

eval:
  eval_delay: 1800  # Every 30 min